export const ERROR_CODES = {
  // Session errors
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_ALREADY_EXISTS: 'SESSION_ALREADY_EXISTS',
  SESSION_NOT_CONNECTED: 'SESSION_NOT_CONNECTED',
  SESSION_QR_EXPIRED: 'SESSION_QR_EXPIRED',
  SESSION_CREATION_FAILED: 'SESSION_CREATION_FAILED',
  SESSION_UNAUTHORIZED: 'SESSION_UNAUTHORIZED',

  // Message errors
  MESSAGE_SEND_FAILED: 'MESSAGE_SEND_FAILED',
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  INVALID_PHONE_NUMBER: 'INVALID_PHONE_NUMBER',
  MESSAGE_CONTENT_EMPTY: 'MESSAGE_CONTENT_EMPTY',

  // Rate limit errors
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  SESSION_IN_COOLDOWN: 'SESSION_IN_COOLDOWN',

  // Broadcast errors
  BROADCAST_NOT_FOUND: 'BROADCAST_NOT_FOUND',
  BROADCAST_INVALID_RECIPIENTS: 'BROADCAST_INVALID_RECIPIENTS',
  BROADCAST_ALREADY_RUNNING: 'BROADCAST_ALREADY_RUNNING',

  // Authentication errors
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',

  // External service errors
  OPENAI_API_ERROR: 'OPENAI_API_ERROR',
  RAJAONGKIR_API_ERROR: 'RAJAONGKIR_API_ERROR',
  LARAVEL_API_ERROR: 'LARAVEL_API_ERROR',

  // Database errors
  DATABASE_ERROR: 'DATABASE_ERROR',
  DATABASE_CONNECTION_FAILED: 'DATABASE_CONNECTION_FAILED',

  // General errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
